/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/character.glb -o src/components/Character.jsx -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";

export function Character({ animation, lightingAction, ...props }) {
  console.log('Character component render - animation:', animation, 'lightingAction:', lightingAction);
  
  // Extra debug for Light animation
  if (lightingAction || animation === 'light') {
    console.log('🎭 LIGHT ANIMATION DEBUG:', { animation, lightingAction, received: animation });
  }
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/MeshTintCharacter.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Debug: Log available animations and nodes
    // console.log('MeshTintCharacter: Available nodes:', Object.keys(nodes || {}));
    // console.log('MeshTintCharacter: Available materials:', Object.keys(materials || {}));
    // if (animations && animations.length > 0) {
    //   console.log('MeshTintCharacter: Available animations:', animations.map(anim => anim.name));
    //   console.log('MeshTintCharacter: Available actions:', Object.keys(actions || {}));
    // }
    
    if (actions && animation) {
      // Map animation names to match your character animations: Idle, Walk, Run, Jump, LightCandle, Falling
      let animationName = animation;
      if (animation === 'idle') animationName = 'Idle';
      if (animation === 'walk') animationName = 'Walk';
      if (animation === 'run') animationName = 'Run';
      if (animation === 'jump') animationName = 'Jump';
      if (animation === 'light') animationName = 'LightCandle';
      if (animation === 'fall') animationName = 'Falling';
      // Fallback for unsupported animations (cast, etc.) -> use Idle
      if (animation === 'cast') animationName = 'Idle';
      
      console.log('MeshTintCharacter: Transitioning to animation:', animationName, 'for requested:', animation, 'lightingAction:', lightingAction);
      
      if (actions[animationName]) {
        // Use crossfade for Reach animation and when transitioning FROM Reach
        const isTransitioningFromReach = Object.values(actions).some(action => 
          action && action.isRunning() && action.getClip().name === 'LightCandle'
        );
        
        if (animationName === 'LightCandle' || isTransitioningFromReach) {
          Object.entries(actions).forEach(([name, action]) => {
            if (action && typeof action.fadeOut === 'function') {
              if (name === animationName) {
                // Fade in the target animation smoothly
                action.reset().fadeIn(0.1).play();
              } else {
                // Fade out other animations
                action.fadeOut(0.1);
              }
            }
          });
        } else {
          // Use immediate transitions for other animations
          Object.entries(actions).forEach(([name, action]) => {
            if (action && name !== animationName) {
              action.stop();
            }
          });
          
          const targetAction = actions[animationName];
          if (targetAction) {
            targetAction.reset();
            targetAction.setEffectiveTimeScale(1);
            targetAction.setEffectiveWeight(1);
            targetAction.play();
          }
        }
      } else {
        // console.warn('MeshTintCharacter: Animation not found:', animationName);
        // Fallback to Idle
        if (actions['Idle']) {
          Object.values(actions).forEach(action => {
            if (action && typeof action.fadeOut === 'function') {
              action.fadeOut(0.1);
            }
          });
          actions['Idle'].reset().fadeIn(0.1).play();
        }
      }
    }
    
    return () => {
      if (actions && animation) {
        Object.values(actions).forEach(action => {
          if (action && typeof action.fadeOut === 'function') {
            action.fadeOut(0.24);
          }
        });
      }
    };
  }, [animation, animations, actions, nodes, materials]);



  // Use a generic primitive approach until we know the node structure
  const primitiveObject = nodes.Scene || nodes._rootJoint || nodes.Root || Object.values(nodes)[0];
  // console.log('MeshTintCharacter: Using primitive object:', primitiveObject?.name, primitiveObject?.type);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={primitiveObject} />
    </group>
  );
}

useGLTF.preload("/models/MeshTintCharacter.glb");

