/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/character.glb -o src/components/Character.jsx -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";

export function Character({ animation, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/MeshTintCharacter.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Debug: Log available animations and nodes
    // console.log('MeshTintCharacter: Available nodes:', Object.keys(nodes || {}));
    // console.log('MeshTintCharacter: Available materials:', Object.keys(materials || {}));
    // if (animations && animations.length > 0) {
    //   console.log('MeshTintCharacter: Available animations:', animations.map(anim => anim.name));
    //   console.log('MeshTintCharacter: Available actions:', Object.keys(actions || {}));
    // }
    
    if (actions && animation) {
      // Map animation names - capitalize first letter to match MeshTintCharacter animations
      let animationName = animation;
      if (animation === 'idle') animationName = 'Idle';
      if (animation === 'walk') animationName = 'Walk';
      if (animation === 'run') animationName = 'Run';
      if (animation === 'jump') animationName = 'Jump';
      if (animation === 'fall') animationName = 'Falling';
      if (animation === 'cast') animationName = 'Casting';
      if (animation === 'light') animationName = 'Light';
      
      console.log('MeshTintCharacter: Transitioning to animation:', animationName, 'for requested:', animation);
      
      if (actions[animationName]) {
        // Crossfade: fade out all other animations while fading in the new one
        Object.entries(actions).forEach(([name, action]) => {
          if (action && typeof action.fadeOut === 'function') {
            if (name === animationName) {
              // Fade in the target animation
              action.reset().fadeIn(0.4).play();
            } else {
              // Fade out other animations
              action.fadeOut(0.4);
            }
          }
        });
      } else {
        // console.warn('MeshTintCharacter: Animation not found:', animationName);
        // Fallback to Idle
        if (actions['Idle']) {
          Object.values(actions).forEach(action => {
            if (action && typeof action.fadeOut === 'function') {
              action.fadeOut(0.4);
            }
          });
          actions['Idle'].reset().fadeIn(0.4).play();
        }
      }
    }
    
    return () => {
      if (actions && animation) {
        Object.values(actions).forEach(action => {
          if (action && typeof action.fadeOut === 'function') {
            action.fadeOut(0.24);
          }
        });
      }
    };
  }, [animation, animations, actions, nodes, materials]);



  // Use a generic primitive approach until we know the node structure
  const primitiveObject = nodes.Scene || nodes._rootJoint || nodes.Root || Object.values(nodes)[0];
  // console.log('MeshTintCharacter: Using primitive object:', primitiveObject?.name, primitiveObject?.type);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={primitiveObject} />
    </group>
  );
}

useGLTF.preload("/models/MeshTintCharacter.glb");

