/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/character.glb -o src/components/Character.jsx -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";

export function Character({ animation, lightingAction, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/character.glb");
  const { actions } = useAnimations(animations, group);
  const armBoneRef = useRef();
  const torchRef = useRef();
  const flameMaterialRef = useRef();
  const particleSystemRef = useRef();
  const coreLightRef = useRef();

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);

  // Single useFrame with all animations combined
  useFrame((state) => {
    // Arm rotation - completely override animation to keep torch forward
    if (armBoneRef.current) {
      // Create target rotation and directly apply it to override the running animation
      const torchRotation = new THREE.Euler(Math.PI/0.5, -Math.PI/6, Math.PI/2, 'XYZ');
      const torchQuaternion = new THREE.Quaternion().setFromEuler(torchRotation);

      // Completely override animation (use copy instead of slerp to prevent lag)
      armBoneRef.current.quaternion.copy(torchQuaternion);
    }


    // Flame material animation
    if (flameMaterialRef.current) {
      flameMaterialRef.current.uniforms.time.value = state.clock.elapsedTime;
    }

    // Torch light flickering
    if (torchRef.current) {
      const time = state.clock.elapsedTime;
      // Create realistic fire flicker
      const flicker = Math.sin(time * 10) * 0.1 +
                      Math.sin(time * 15) * 0.05 +
                      Math.sin(time * 7) * 0.08;

      torchRef.current.intensity = 3 + flicker;

      // Slight color variation
      const colorFlicker = 0.1 + flicker * 0.05;
      torchRef.current.color.setHSL(0.08, 0.9, 0.5 + colorFlicker);
    }

    // Flicker the core light too
    if (coreLightRef.current) {
      const time = state.clock.elapsedTime;
      const coreFlicker = Math.sin(time * 12) * 0.2 + Math.sin(time * 20) * 0.1;
      coreLightRef.current.intensity = 1.5 + coreFlicker;
    }

    // Animate particles with more natural movement
    if (particleSystemRef.current) {
      const positions = particleSystemRef.current.geometry.attributes.position.array;
      const velocities = particleSystemRef.current.geometry.attributes.velocity.array;
      const opacities = particleSystemRef.current.geometry.attributes.opacity.array;

      for (let i = 0; i < positions.length / 3; i++) {
        const i3 = i * 3;

        // Update positions
        positions[i3] += velocities[i3];
        positions[i3 + 1] += velocities[i3 + 1];
        positions[i3 + 2] += velocities[i3 + 2];

        // Add slight wind/turbulence
        positions[i3] += Math.sin(state.clock.elapsedTime * 2 + i) * 0.001;

        // Fade out as particles rise
        const height = positions[i3 + 1]; // Height from flame base
        opacities[i] = Math.max(0, 1 - height * 1.5);

        // Reset particles that go too high or fade out
        if (positions[i3 + 1] > 1.2 || opacities[i] <= 0) {
          positions[i3] = (Math.random() - 0.5) * 0.05;
          positions[i3 + 1] = 0.0 + Math.random() * 0.2;
          positions[i3 + 2] = (Math.random() - 0.5) * 0.05;
          opacities[i] = Math.random() * 0.5 + 0.5;

          // Refresh velocity for variety
          velocities[i3] = (Math.random() - 0.5) * 0.01;
          velocities[i3 + 1] = Math.random() * 0.03 + 0.01;
          velocities[i3 + 2] = (Math.random() - 0.5) * 0.01;
        }
      }

      particleSystemRef.current.geometry.attributes.position.needsUpdate = true;
      particleSystemRef.current.geometry.attributes.opacity.needsUpdate = true;
    }
  });

  // Attach torch to hand bone once when component mounts
  useEffect(() => {
    if (nodes._rootJoint) {
      // Find bones (keeping your existing bone-finding logic)
      const findBone = (name) => {
        const traverse = (obj) => {
          if (obj.name.toLowerCase().includes(name.toLowerCase())) return obj;
          for (const child of obj.children) {
            const found = traverse(child);
            if (found) return found;
          }
          return null;
        };
        return traverse(nodes._rootJoint);
      };

      const handBone = findBone('wrist_r') || findBone('hand_r') || findBone('right') || findBone('wrist');
      const armBone = findBone('shoulder_r') || findBone('arm_r') || findBone('upperarm_r') || findBone('shoulder');

      if (handBone) {
        // Store arm bone reference - DON'T set initial rotation here
        if (armBone) {
          armBoneRef.current = armBone;
          // Removed initial rotation - will be set in useFrame instead
        }

        // Create torch group
        const torchGroup = new THREE.Group();

        // Torch handle
        const handleGeometry = new THREE.CylinderGeometry(0.04, 0.05, 1.2, 8);
        const handleMaterial = new THREE.MeshStandardMaterial({
          color: '#8B4513',
          roughness: 0.8,
          metalness: 0.2
        });
        const handle = new THREE.Mesh(handleGeometry, handleMaterial);
        handle.position.set(0, -0.6, 0);
        handle.castShadow = true;
        torchGroup.add(handle);

        // Torch head
        const headGeometry = new THREE.CylinderGeometry(0.12, 0.08, 0.3, 8);
        const headMaterial = new THREE.MeshStandardMaterial({
          color: '#654321',
          roughness: 0.9
        });
        const head = new THREE.Mesh(headGeometry, headMaterial);
        head.position.set(0, 0.2, 0);
        head.castShadow = true;
        torchGroup.add(head);

        // CREATE ANIMATED FLAME MATERIAL
        const flameMaterial = new THREE.ShaderMaterial({
          uniforms: {
            time: { value: 0 },
            color1: { value: new THREE.Color('#FF6B35') },
            color2: { value: new THREE.Color('#FFD700') },
          },
          vertexShader: `
            uniform float time;
            varying vec2 vUv;
            void main() {
              vUv = uv;
              vec3 pos = position;
              // Wave distortion for flame movement
              pos.x += sin(time * 10.0 + position.y * 3.0) * 0.02;
              pos.z += cos(time * 8.0 + position.y * 3.0) * 0.02;
              gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
            }
          `,
          fragmentShader: `
            uniform vec3 color1;
            uniform vec3 color2;
            uniform float time;
            varying vec2 vUv;
            void main() {
              // Gradient from orange to yellow
              vec3 color = mix(color1, color2, vUv.y + sin(time * 5.0) * 0.1);
              float alpha = 1.0 - vUv.y * 0.3; // Fade at top
              gl_FragColor = vec4(color, alpha);
            }
          `,
          transparent: true,
          side: THREE.DoubleSide
        });

        // Store reference for animation
        flameMaterialRef.current = flameMaterial;

        // APPLY THE ANIMATED MATERIAL TO THE FLAME
        const flameGeometry = new THREE.ConeGeometry(0.16, 0.4, 6);
        const flame = new THREE.Mesh(flameGeometry, flameMaterial); // USE THE SHADER MATERIAL
        flame.position.set(0, 0.5, 0);
        torchGroup.add(flame);

        // CREATE PARTICLE SYSTEM with better visuals
        const particleCount = 30; // Increased count
        const particles = new THREE.BufferGeometry();
        const positions = new Float32Array(particleCount * 3);
        const velocities = new Float32Array(particleCount * 3);
        const sizes = new Float32Array(particleCount); // Individual particle sizes
        const opacities = new Float32Array(particleCount); // Individual opacities

        for (let i = 0; i < particleCount; i++) {
          const i3 = i * 3;
          // Start positions overlapping with flame
          positions[i3] = (Math.random() - 0.5) * 0.05;
          positions[i3 + 1] = 0.0 + Math.random() * 0.2; // Start at flame base, overlap throughout
          positions[i3 + 2] = (Math.random() - 0.5) * 0.05;

          // More varied velocities with upward bias
          velocities[i3] = (Math.random() - 0.5) * 0.01;
          velocities[i3 + 1] = Math.random() * 0.03 + 0.01; // Mostly upward
          velocities[i3 + 2] = (Math.random() - 0.5) * 0.01;

          // Random sizes for variety
          sizes[i] = Math.random() * 0.015 + 0.005; // Smaller particles
          opacities[i] = Math.random() * 0.5 + 0.5;
        }

        particles.setAttribute('position', new THREE.BufferAttribute(positions, 3));
        particles.setAttribute('velocity', new THREE.BufferAttribute(velocities, 3));
        particles.setAttribute('size', new THREE.BufferAttribute(sizes, 1));
        particles.setAttribute('opacity', new THREE.BufferAttribute(opacities, 1));

        // Create a circular sprite texture for particles
        const canvas = document.createElement('canvas');
        canvas.width = 64;
        canvas.height = 64;
        const ctx = canvas.getContext('2d');

        // Create gradient circle
        const gradient = ctx.createRadialGradient(32, 32, 0, 32, 32, 32);
        gradient.addColorStop(0, 'rgba(255, 255, 200, 1)'); // Bright yellow-white center
        gradient.addColorStop(0.3, 'rgba(255, 200, 100, 1)'); // Orange
        gradient.addColorStop(0.7, 'rgba(255, 100, 50, 0.5)'); // Red-orange
        gradient.addColorStop(1, 'rgba(255, 50, 0, 0)'); // Transparent edge

        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, 64, 64);

        const particleTexture = new THREE.CanvasTexture(canvas);

        const particleMaterial = new THREE.PointsMaterial({
          size: 0.08, // Base size (will be multiplied by individual sizes)
          map: particleTexture,
          transparent: true,
          opacity: 0.9,
          blending: THREE.AdditiveBlending,
          depthWrite: false, // Prevents z-fighting
          vertexColors: false,
          sizeAttenuation: true, // Particles get smaller with distance
        });

        const particleSystem = new THREE.Points(particles, particleMaterial);
        particleSystem.position.set(0, 0.5, 0);
        torchGroup.add(particleSystem);

        // Store reference for animation
        particleSystemRef.current = particleSystem;

        // LIGHTS
        // Main warm point light
        const mainLight = new THREE.PointLight('#FF6B35', 3, 6, 2);
        mainLight.position.set(0, 0.5, 0);
        mainLight.castShadow = true;
        mainLight.shadow.mapSize.width = 1024;
        mainLight.shadow.mapSize.height = 1024;
        mainLight.shadow.camera.near = 0.1;
        mainLight.shadow.camera.far = 8;
        mainLight.shadow.radius = 10;
        mainLight.shadow.blurSamples = 5;
        torchGroup.add(mainLight);

        // Store reference for flickering
        torchRef.current = mainLight;

        // Core light
        const coreLight = new THREE.PointLight('#FFD700', 1.5, 2, 2);
        coreLight.position.set(0, 0.4, 0);
        torchGroup.add(coreLight);
        coreLightRef.current = coreLight;

        // Spot light for directional glow
        const spotLight = new THREE.SpotLight('#FF8C00', 1, 5, Math.PI / 4, 0.5);
        spotLight.position.set(0, 0.5, 0);
        spotLight.target.position.set(0, 2, 0);
        torchGroup.add(spotLight);
        torchGroup.add(spotLight.target);

        // Position and attach torch to hand
        torchGroup.position.set(-1.2, 0.5, -0.3);
        torchGroup.rotation.set(-Math.PI/4, 0.15, Math.PI/2.5);
        handBone.add(torchGroup);
      }
    }
  }, [nodes]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="fall_guys">
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials.Material}
            skeleton={nodes.body.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="eye"
            geometry={nodes.eye.geometry}
            material={materials.Material}
            skeleton={nodes.eye.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="hand-"
            geometry={nodes["hand-"].geometry}
            material={materials.Material}
            skeleton={nodes["hand-"].skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="leg"
            geometry={nodes.leg.geometry}
            material={materials.Material}
            skeleton={nodes.leg.skeleton}
            castShadow
            receiveShadow
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/character.glb");